httpport: "8080"
grpcport: "9000"

jwtsecretkey: "MySecretKey123"

postgres:
  host: "pg"
  port: "5432"
  username: "puregradeuser"
  password: "pgpw4puregrade"
  dbname: "puregradedb"
  sslmode: "disable" # or "enable"

redis:
  host: "redis"
  port: "6379"
  password: "redispw4puregrade"