version: "3.9"
services:
  pg:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: "puregradedb"
      POSTGRES_USER: "puregradeuser"
      POSTGRES_PASSWORD: "pgpw4puregrade"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - .:/var/lib/postgresql/data
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U puregradeuser -d puregradedb"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=redispw4puregrade
    restart: always
    volumes:
      - .:/bitnami/redis/data
    # ports:
    #   - 6379:6379

  server:
    build: "."
    container_name: server
    hostname: "0.0.0.0"
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      - pg
